name: chapter_1_examples
version: 1.0.0
description: Examples for Chapter 1 in the Dart project.

# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
